CREATE DATABASE BANK;
\c BANK;

CREATE TABLE IF NOT EXISTS BANK (
    BankID SERIAL PRIMARY KEY,
    BankName VARCHAR(35) NOT NULL,
    BankMoney NUMERIC(15,2) NOT NULL CHECK (BankMoney >= 0),
    NoOfBranches INT NOT NULL CHECK (NoOfBranches >= 0)
);

CREATE TABLE IF NOT EXISTS BRANCH (
    BranchID SERIAL PRIMARY KEY,
    BranchAdd VARCHAR(255) NOT NULL,
    BankID INT,
    FOREIGN KEY (BankID) REFERENCES BANK(BankID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
    EmployeeID SERIAL PRIMARY KEY,
    Name VARCHAR(25) NOT NULL,
    BranchID INT,
    FOREIGN KEY (BranchID) REFERENCES BRANCH(BranchID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS USERS (  
    UserID SERIAL PRIMARY KEY,
    Name VARCHAR(25) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    MobileNumber VARCHAR(10) NOT NULL CHECK (char_length(MobileNumber) = 10)
);

CREATE TABLE IF NOT EXISTS ACCOUNT (
    AccountNo SERIAL PRIMARY KEY,
    Balance NUMERIC(15,2) NOT NULL CHECK (Balance >= 0),
    UserID INT,
    BranchID INT,
    FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE,
    FOREIGN KEY (BranchID) REFERENCES BRANCH(BranchID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LOAN (
    LoanID SERIAL PRIMARY KEY,
    LoanAmount NUMERIC(15,2) NOT NULL CHECK (LoanAmount > 0),
    Duration INT NOT NULL CHECK (Duration > 0),
    Interest NUMERIC(5,2) NOT NULL CHECK (Interest BETWEEN 0 AND 100),
    LoanType VARCHAR(50) NOT NULL,
    IssueDate DATE NOT NULL,
    UserID INT,
    BankID INT,
    FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE,
    FOREIGN KEY (BankID) REFERENCES BANK(BankID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRANSACTION_HISTORY (  
    TransactionID SERIAL PRIMARY KEY,
    TransactionAmount NUMERIC(15,2) NOT NULL CHECK (TransactionAmount > 0),
    TransactionTime TIMESTAMP NOT NULL,
    BranchID INT,
    AccountNo1 INT,
    AccountNo2 INT,
    FOREIGN KEY (BranchID) REFERENCES BRANCH(BranchID) ON DELETE SET NULL,
    FOREIGN KEY (AccountNo1) REFERENCES ACCOUNT(AccountNo) ON DELETE CASCADE,
    FOREIGN KEY (AccountNo2) REFERENCES ACCOUNT(AccountNo) ON DELETE CASCADE
);
